### ISSUE TITLE
The app crashes when i try to check for updates.

### ISSUE THREAD

**Issue by fnldstntn** [hemker/apkgrabber#20]
https://del.dog/ahetikinep
The app crashes when i try to check for updates. I it it's because the Turkish language. The app works fine when i change the phone language to English.

**Comment by hemker** [comment]
Seems to crash because of the 'ü' char. Will take a look at that.

**Comment by sanjayen** [comment]
Getting consistent FCs with the new version which was not the case with the older ones. Here's the stack;
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{6bbb73d position=4 id=-1, oldPos=3, pLpos:3 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{38eb5b6 VFED..... ......I. 0,221-1080,1680 #7f1000b8 app:id/list_view}, adapter:de.apkgrabber.adapter.UpdaterAdapter@9ef3943, layout:android.support.v7.widget.LinearLayoutManager@fe502b7, context:de.apkgrabber.activity.MainActivity_@e743a38
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:174)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:112)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:174)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:112)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:174)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:112)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:174)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:112)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at com.android.internal.policy.DecorView.onLayout(Unknown Source:1)
	at android.view.View.layout(Unknown Source:83)
	at android.view.ViewGroup.layout(Unknown Source:27)
	at android.view.ViewRootImpl.performLayout(Unknown Source:32)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:1853)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:32)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:106)
	at android.view.Choreographer.doFrame(Unknown Source:212)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:152)
	at android.app.ActivityThread.main(Unknown Source:68)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:203)

**Comment by Dratas** [comment]
some issue for me to,app crashes if i mark for example google play,apkmirror,apk cure 😃😱😱😱😱😱LG P710 with kitkat 4.4.2

**Comment by hemker** [comment]
@fnldstntn should be fixed in current release. Please confirm.

**Comment by fnldstntn** [comment]
@hemker Yes, it is fixed. Thanks.
