### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kgursu** [hemker/apkgrabber#57]
Can't see anything...
Here's the crash report by Scoop:
FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 6474
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:505)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	... 1 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: com.xiaomi.scanner
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:395)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:377)
	at android.app.ApplicationPackageManager.getApplicationIcon(ApplicationPackageManager.java:1257)
	at de.apkgrabber.adapter.UpdaterViewHolder.bind(UpdaterViewHolder.kt:52)
	at de.apkgrabber.adapter.UpdaterAdapter.onBindViewHolder(UpdaterAdapter.kt:160)
	at de.apkgrabber.adapter.UpdaterAdapter.onBindViewHolder(UpdaterAdapter.kt:26)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7198)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:751)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6723)
	... 3 more

**Comment by Kaz1993** [comment]
Looks like the com.xiaomi.scanner does not provide a valid name in it's package manager entry and so it's causing this exception:

Caused by: android.content.pm.PackageManager$NameNotFoundException: com.xiaomi.scanner

**Comment by hemker** [comment]
@Kaz1993 @kgursu so this problem seems to be caused by a third party app misconfiguration?

**Comment by pashamcr** [comment]
Android 4.2 - crash on startup, all versions 1.6+
[de.apkgrabber.txt](https://github.com/hemker/apkgrabber/files/3508566/de.apkgrabber.txt)

**Comment by pashamcr** [comment]
https://github.com/hemker
Android 4.2 - crash on startup, all versions 1.6+
[de.apkgrabber.txt](https://github.com/hemker/apkgrabber/files/3508699/de.apkgrabber.txt)

**Comment by pashamcr** [comment]
> 
> 
> @Kaz1993 @kgursu so this problem seems to be caused by a third party app misconfiguration?

Android 4.2 - crash on startup, all versions 1.6+
[log](https://github.com/hemker/apkgrabber/files/3508765/de.apkgrabber.txt)
